call addPlayer('Colin');
call addPlayer('David');
call addPlayer('James');
call addPlayer('Matthew');
call addPlayer('Mary');
call addPlayer('Pamela');
call addPlayer('Alpha');
call addPlayer('Beta');
call addPlayer('Gamma');
call addPlayer('Delta');
call addPlayer('Kappa');
call addPlayer('Theta');
call addPlayer('Sigma');
call addPlayer('Apple');
call addPlayer('Bacon');
call addPlayer('Copper');
call addPlayer('Dipper');
call addPlayer('Echo');
call addPlayer('Foxtrot');
call addPlayer('Golf');
call addPlayer('Hotel');
call addPlayer('India');
call addPlayer('Juliet');
call addPlayer('Kilo');
call addPlayer('Liger');
call addPlayer('November');
call addPlayer('Oscar');
call addPlayer('Peter');
call addPlayer('Quayle');
call addPlayer('Romeo');
call addPlayer('Sierra');

INSERT INTO tblscoringscheme (description) VALUES ('10-6-3-1 Scoring');
INSERT INTO tblscoring (_fk_scoringscheme, numplayers, rank, pointsforrank) VALUES ((SELECT _key from tblscoringscheme where description = '10-6-3-1 Scoring' LIMIT 1), 3, 1, 10);
INSERT INTO tblscoring (_fk_scoringscheme, numplayers, rank, pointsforrank) VALUES ((SELECT _key from tblscoringscheme where description = '10-6-3-1 Scoring' LIMIT 1), 3, 2, 5);
INSERT INTO tblscoring (_fk_scoringscheme, numplayers, rank, pointsforrank) VALUES ((SELECT _key from tblscoringscheme where description = '10-6-3-1 Scoring' LIMIT 1), 3, 3, 1);
INSERT INTO tblscoring (_fk_scoringscheme, numplayers, rank, pointsforrank) VALUES ((SELECT _key from tblscoringscheme where description = '10-6-3-1 Scoring' LIMIT 1), 4, 1, 10);
INSERT INTO tblscoring (_fk_scoringscheme, numplayers, rank, pointsforrank) VALUES ((SELECT _key from tblscoringscheme where description = '10-6-3-1 Scoring' LIMIT 1), 4, 2, 6);
INSERT INTO tblscoring (_fk_scoringscheme, numplayers, rank, pointsforrank) VALUES ((SELECT _key from tblscoringscheme where description = '10-6-3-1 Scoring' LIMIT 1), 4, 3, 3);
INSERT INTO tblscoring (_fk_scoringscheme, numplayers, rank, pointsforrank) VALUES ((SELECT _key from tblscoringscheme where description = '10-6-3-1 Scoring' LIMIT 1), 4, 4, 1);

CALL previewFourPlayerScoreEntry(10101, 'Beta', 10293480, 'Mary', 29873500, 'Sierra', 39865050, 'Quayle', 46382950);